
const SCREEN_WIDTH = 800
const SCREEN_HEIGHT = 600
const SPRITE_WIDTH = 32
const SPRITE_HEIGHT = 64
const VELOCITY = 2
const SPAWN_ZONE_LEFT_BOUND = SCREEN_WIDTH / 4
const SPAWN_ZONE_RIGHT_BOUND = (SCREEN_WIDTH / 4) * 3

module.exports = {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  SPRITE_WIDTH,
  SPRITE_HEIGHT,
  VELOCITY,
  SPAWN_ZONE_LEFT_BOUND,
  SPAWN_ZONE_RIGHT_BOUND
}
