
const SCREEN_WIDTH = 800
const SCREEN_HEIGHT = 600
const SPRITE_WIDTH = 32
const SPRITE_HEIGHT = 64
const VELOCITY = 1
const YES_BOUND = SCREEN_WIDTH/4
const NO_BOUND = (SCREEN_WIDTH/4)*3

module.exports = {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  VELOCITY,
  YES_BOUND,
  NO_BOUND
}
